name = "animotem-ratings"
main = "src/index.js"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "animotem-ratings"
database_id = "5796e0c0-6bac-49e1-ba26-231b08c94282"
